
modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
[[mods]]
modId="ecbtcws"
version="${file.jarVersion}"
displayName="Enderite Command Block Tools"
logoFile="enderite_cmd_paxel.png"
credits="Bagheerawithae"
authors="Bagheerawithae"
description='''
An addon for cwsm & enderitemod.
'''
[[dependencies.ecbtcws]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ecbtcws]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ecbtcws]]
    modId="enderitemod"
    mandatory=true
    versionRange="[1.5.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ecbtcws]]
    modId="witherstormmod"
    mandatory=true
    versionRange="[4.0.1.1,)"
    ordering="NONE"
    side="BOTH"